import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Layout } from '../components/layout';
import {
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';
import { WINNING_PROJECT } from '../lib/constants/constant';
import dynamic from 'next/dynamic';
import Outro from '../components/outro';
import Intro from '../components/intro';
import Project from '../components/cards';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

const Gallery = dynamic(() => import('../components/gallery'));
const SlantingCards = dynamic(() => import('../components/slanting-cards'));
const Feedbacks = dynamic(() => import('./feedbacks'));

export default function Index({ publication }: Props) {
	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>Shivam Katare</title>
					<meta
						name="Shivam Katare: Developer | Open Source Contributor | Technical Writer"
						content="Shivam Katare"
					/>
					<meta property="twitter:description" content="Shivam Katare" />
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd("Shivam-Katare")),
						}}
					/>
				</Head>
				<Container className="mx-auto flex max-w-3xl flex-col items-stretch gap-10 px-5 py-10">
					<Intro />
					<Gallery />
					<div className='text-center'>
						I write about web development, including JavaScript, React, Next.js, Tailwind CSS, and more.
						Also, I share my experiences as a developer and the latest tech industry trends.
					</div>
					<Project />
					<div className='text-center'>
						<p>
							I participate in hackathons and writeathons to improve my skills, learn new technologies, and connect with other developers. Below are some of my winning projects and articles.
						</p>
					</div>
					{WINNING_PROJECT.map((project) => (
						<SlantingCards key={project.title} title={project.title} description={project.description} link={project.link} image={project.image} />
					))}
					<h3 className='text-[20px] font-normal text-center'>A collection of kind words and positive comments from others. 😊</h3>
					<Feedbacks />
					<Outro />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 1,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};